### ISSUE TITLE
reproducible crash RunTimeException

### ISSUE THREAD

**Issue by christf** [OpenLauncherTeam/openlauncher#452] opened 2018-11-26 08:34 UTC
#### General information

* Openlauncher 0.6.0
* Android 5.1

#### Description
when starting the phone, openlauncher immediately crashes with a RunTimeException. Will attach via Mail from phone after this issue is created.

**Comment by christf** [comment] 2018-11-26 09:22
Build version: 0.6.0 
Build date: 1980-01-01 00:00:00 
Current date: 2018-11-26 09:04:43 
Device: Sony D5503 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity}: java.lang.RuntimeException: system server dead?
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
	at android.app.ActivityThread.access$800(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5389)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: java.lang.RuntimeException: system server dead?
	at android.appwidget.AppWidgetHost.startListening(AppWidgetHost.java:161)
	at com.benny.openlauncher.activity.HomeActivity.init(HomeActivity.java:219)
	at com.benny.openlauncher.activity.HomeActivity.onCreate(HomeActivity.java:213)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
	... 10 more
Caused by: android.os.TransactionTooLargeException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:496)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.startListening(IAppWidgetService.java:437)
	at android.appwidget.AppWidgetHost.startListening(AppWidgetHost.java:157)
	... 15 more

**Comment by dkanada** [comment] 2018-12-29 13:42
I have no idea where this came from, but what model of phone are you using? A quick search shows a lot of results for phones with older hardware so that might be the cause.

**Comment by gsantner** [comment] 2019-04-28 16:36
cannot reproduce, looks like something very device/os specific and may be fixed in dev version already.

**Closed by gsantner** 2019-04-28 16:36 UTC
