### ISSUE TITLE
Add to home screen (A2HS) does not work

### ISSUE THREAD

**Issue by fernandomana** [OpenLauncherTeam/openlauncher#530] opened 2019-12-02 20:20 UTC
#### General Information

* **OpenLauncher Version:** 0.7.1 (39)
* **Android Version:** 9
* **Custom ROM:** LineageOS
* **Install Source:** F-Droid

#### Description

The A2HS feature of web browsers does not work when open launcher is set as default launcher app.

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#What_browsers_support_A2HS

**Comment by sbadux** [comment] 2020-01-09 21:33
I'm using it on /e/OS Android Pie based ROM and I can't add any shortcut from chromium to the Home Screen. It says "Added to the home screen" but the shortcut don't appear in the home screen

**Comment by symbioquine** [comment] 2020-02-11 01:04
This is a really important feature!

Also maybe a duplicate of https://github.com/OpenLauncherTeam/openlauncher/issues/522

**Comment by gsantner** [comment] 2021-01-25 21:29
use.search. #522 #637

**Closed by gsantner** 2021-01-25 21:29 UTC
