### ISSUE TITLE
[Bug]: Updation of the Widgets' displayed content mostly isn't up to date

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#534] opened 2019-12-05 20:14 UTC
#### General Information

* **OpenLauncher Version:** 0.7.2 (40)
* **Android Version:** 8.1 Oreo
* **Custom ROM:** no, BQ stock ROM (Aquaris X Pro)
* **Install Source:** F-Droid
* **Specialities:** rooted with Magisk, running EdXposed

#### Description

The content of the widgets placed at OpenLauncher's screens seems to be updated only seldom or only under some conditions that I want able to ascertain up to now.
**For example:** I have placed a K-9 mail widget for showing me an overview of all emails. But even if I got new emails a long time ago (some minutes, half of an hour...), they aren't displayed by the widget.

**Comment by Windyo** [comment] 2019-12-21 15:03
Same bug here. 
For example if I have a calendar widget, clicking to show next month will seem to do nothing. If I move the widget from it's position it forces an update and the right data is displayed. 

Same with SoundCloud.

In shirt one can say that all widgets are broken.

**Comment by just-Nob** [comment] 2020-01-03 15:58
Unfortunately currently unusable for any widget. None of them is being updated!
In that version (v.0.7.2 (40)), the launcher is not much more than a little blown-up app drawer.

I'm thinking about to switch back to v.0.6.1 (which worked well also for widgets!) until that problem is solved.

**Comment by mase76** [comment] 2020-01-16 05:52
I can confirm the widgets issues.. Even the lineage clock completely disappears after some time.

**Comment by Franestra** [comment] 2020-05-20 17:07
I am having this problem as well... having a clock widget makes this extra clear, since the time does not get properly updated

**Comment by gsantner** [comment] 2021-01-25 21:53
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:

**Closed by gsantner** 2021-01-25 21:53 UTC
