### ISSUE TITLE
crash when adding app to the dock after an update removed the icon

### ISSUE THREAD

**Issue by klauf** [OpenLauncherTeam/openlauncher#162] opened 2017-06-11 08:37 UTC
Hi 
Since 0.5.1 my first crash in what, 2-3weeks? Skype app got updated then I realized the icon was not in the dock anymore. I tried to put it back but received the following complaint:

Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-11 10:32:58 
Device: LeMobile LEX829 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
	at com.benny.openlauncher.util.AppManager.findApp(AppManager.java:64)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.<init>(GroupIconDrawable.java:48)
	at com.benny.openlauncher.widget.AppItemView$Builder.setGroupItem(AppItemView.java:234)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:92)
	at com.benny.openlauncher.widget.Dock.addItemToPage(Dock.java:210)
	at com.benny.openlauncher.widget.Dock.initDockItem(Dock.java:60)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:250)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:235)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

Now I guess I'll have to uninstall - reinstall OL again :) 
I want to use the opportunity to say thanks, OL is now IMO stable enough to stay my daily driver!

**Comment by gsantner** [comment] 2017-06-11 09:16
Please check other issues before creating. This is a duplicate of the issue before this one.

**Comment by gsantner** [comment] 2017-06-11 09:16
#161

**Closed by gsantner** 2017-06-11 09:16 UTC
