### ISSUE TITLE
Adding ability to change single app icons

### ISSUE THREAD

**Issue by TobiasDev** [OpenLauncherTeam/openlauncher#453] opened 2018-11-26 21:06 UTC
#### General Information

* **OpenLauncher Version:** 0.6.0
* **Android Version:** 7.1.2
* **Custom ROM:** Eelo
* **Install Source:** F-Droid

#### Description
I love that I can use Icon packs, however when an app isn't included in the pack I usually change it to be something similar, so the theme looks consistent. I didn't find anyway to change single app icons in Open Launcher. Is there a plan for adding this?

**Comment by dkanada** [comment] 2018-11-27 14:32
This is a duplicate of #305 which was actually also opened by you :) we labeled that one help wanted because it is not a simple change. We would accept help to work on this but right now I am not sure when I will be able to add this.

**Closed by dkanada** 2018-11-27 14:32 UTC

**Comment by TobiasDev** [comment] 2018-11-27 15:50
Bah. Sorry! I didn't find an issue about this when I looked... even though I thought I had open one. Sorry.
