### ISSUE TITLE
Widgets don't get updated

### ISSUE THREAD

**Issue by Benjilein** [OpenLauncherTeam/openlauncher#359] opened 2018-03-26 05:07 UTC
I have serveral widgets on the screens. For example: calendar and openTasks. Since Version >= 0.5.8, the widgets don't get updated anymore (only when I restart openLauncher) 
-----------------------------

#### General information

* **App version:** 0.5.8(alpha) and 0.5.10
* **Android Version:** 7.1.1

#### Expected result
**What is expected?** 
Content of widgets gets updated

**What does happen instead?**
Widgets keep displaying the information, when the app was last restarted.

**Comment by juneverse** [comment] 2018-04-01 18:16
I've had this issue for a while now, too. Exact same behaviour that you've mentioned.

App Version: currently 0.5.10
Android Version: 6.0.1

**Comment by ameenross** [comment] 2018-11-14 09:35
I've had this since the update of 0.5.12 to 0.6.0. Didn't have it before the update. Regression?

Android version is: 8.1.0

**Comment by mase76** [comment] 2019-11-27 11:17
Same here with Omniclock and Antennapod. The Widgets aren't updated after some time.

**Comment by gsantner** [comment] 2021-01-25 21:59
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:

**Closed by gsantner** 2021-01-25 21:59 UTC
