### ISSUE TITLE
Minor irritation by zero margin to status bar on home screen introduced in v0.6.0

### ISSUE THREAD

**Issue by calbrecht** [OpenLauncherTeam/openlauncher#444] opened 2018-11-02 10:40 UTC
#### General information

* **App version:** 
v0.6.0 F-Droid
* **System:**
Android 8.0.0
OnePlus 3
OxygenOS 5.0.6

#### Description
First of all, thanks for developing this nice little launcher, very much appreciated :)

From reading https://github.com/OpenLauncherTeam/openlauncher/commit/adc9c3613a5c6c36557e3f67f6f692639031087a i understand this was intended for a nicer view when the search bar is enabled, however i don't use the search bar and for me that introduced an admittedly rather minor esthetical nuisance.
With the configured desktop of 5 cols and 8 rows the topmost row of icons is displayed very close to the bottom of the status bar, where i'd rather see the same margin like from the last row to the bottom of the screen.

Current:
![android_home](https://user-images.githubusercontent.com/1516457/47910665-de8ad780-de93-11e8-824a-fcab7389d1ca.png)

Anticipated:
![android_home_margin](https://user-images.githubusercontent.com/1516457/47910666-de8ad780-de93-11e8-91bb-849423dd24b8.png)

**Comment by dkanada** [comment] 2018-11-03 07:56
I agree with you, it definitly looks worse. This might actually be a bug though, could you do a little bit of testing for me to check the grid layouts? Some helpful screenshots could include the dock and desktop with different background colors, a screenshot of the grid lines when you are dragging an icon around the screen, or a widget on the top and bottom of the desktop to see if there is any unwanted overlap between screen elements. It looks to me like the desktop might be overlapping with the status bar, which shouldn't happen.

**Comment by calbrecht** [comment] 2018-11-03 09:12
@dkanada thanks for the quick response :) i guess (because i never did any android development) this might be introduced by the change of https://github.com/OpenLauncherTeam/openlauncher/commit/adc9c3613a5c6c36557e3f67f6f692639031087a#diff-69cb44c2528e2c2231a3b24e47e00962L38

![image](https://user-images.githubusercontent.com/1516457/47950310-c88f1c80-df50-11e8-96f9-24f18cdc4132.png)
![image](https://user-images.githubusercontent.com/1516457/47950315-d2b11b00-df50-11e8-8853-d2078544e591.png)
![image](https://user-images.githubusercontent.com/1516457/47950317-dfce0a00-df50-11e8-8b06-fdc00818361d.png)

**Comment by dkanada** [comment] 2018-11-03 09:36
Woah, how did you get those lines drawn up on the screen? Also, do you have fullscreen enabled in the app settings? Does restarting the app from the debug settings fix the issue?

**Comment by calbrecht** [comment] 2018-11-03 09:41
Those lines are drawn when in the ```Android Settings -> Developer Options -> [Drawing] -> Show layout bonds``` is selected :D

Fullscreen is not enabled in the app settings, and restarting does not fix the issue.

**Comment by calbrecht** [comment] 2018-11-03 09:43
If i enable fullscreen, all status bar is invisible (guess that is wanted though)

**Comment by dkanada** [comment] 2018-11-03 10:11
What about the system bars color? I am wondering if the status bar is registered with the launcher or not, that could be the issue.

**Comment by dkanada** [comment] 2018-11-03 10:17
Oh! I just ran the F-Droid version and I am getting the same issue. The problem is that after I updated the app F-Droid wouldn't build the update. I then fixed this bug and was happy I caught another issue before F-Droid built the app. Then I fixed the build issue on F-Droid, but it built the old version of the app anyway. This will be fixed in the next update!

**Comment by calbrecht** [comment] 2018-11-03 10:33
Great news :), thank you @dkanada

**Comment by dkanada** [comment] 2018-11-03 11:00
I am going to close this issue, but please open it again if the next F-Droid update doesn't solve the problem!

**Closed by dkanada** 2018-11-03 11:00 UTC
