### ISSUE TITLE
Add Pin Shortcuts support

### ISSUE THREAD

**Issue by trymeouteh** [OpenLauncherTeam/openlauncher#583] opened 2020-04-19 06:27 UTC
Please add pinshortcuts in openlauncher. The webapps app does not allow me to create shortcuts for my webapps on openlauncher because it does not support this.

**Comment by TheoRet** [comment] 2020-05-12 12:49
Is this a duplicate of #568?

In other words, are "pin shortcuts" different from other shortcuts in Android?

**Comment by trymeouteh** [comment] 2020-06-09 00:36
I think it is the same thing worded differently. If you download the Webapps app from F-Droid, and create a webapp such as YouTube and try to make a shortcut of it on your launcher. It will not work on OpenLauncher since OpenLauncher does not allow this.

**Comment by gsantner** [comment] 2021-01-25 21:25
use.search. #522 #637

**Closed by gsantner** 2021-01-25 21:25 UTC
