### ISSUE TITLE
constant crash with high grid density

### ISSUE THREAD

**Issue by klauf** [OpenLauncherTeam/openlauncher#107] opened 2017-05-15 02:36 UTC
Hi all

I randomly get crashes like this one preventing the daily use of this launcher

Build version: 0.4.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-15 04:27:27 
Device: LeMobile LEX829 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:287)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:234)
	at com.benny.openlauncher.widget.Desktop.addItemToPage(Desktop.java:281)
	at com.benny.openlauncher.widget.Desktop.handleOnDropOver(Desktop.java:570)
	at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:223)
	at android.view.View.callDragEventHandler(View.java:20902)
	at android.view.View.dispatchDragEvent(View.java:20893)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1510)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5557)
	at android.view.ViewRootImpl.-wrap7(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3671)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

I searched the already reported issues but am not sure it has already been reported. Any link with the size of the grid I'm using (9x14)?

**Comment by dkanada** [comment] 2017-05-15 02:50
This happens when you drag an app directly from the app drawer into a group, it will be fixed in the next update. For now it can be avoided by dragging apps to the desktop before adding them to a group.

**Closed by dkanada** 2017-05-15 02:50 UTC

**Comment by klauf** [comment] 2017-05-15 03:59
Thanks dkanada for your answer. I'm not working with groups at all. Still, I'll wait for the next update then.

**Comment by dkanada** [comment] 2017-05-15 05:49
That is odd, it looks like the crash came from getGroupIconDrawable which I thought was only called when there were group items. Not sure what the issue is then, but my commit from earlier might have fixed it regardless. Try out the next update when we finish up the new settings and let me know if you still get that error message.

**Comment by klauf** [comment] 2017-05-20 22:35
Thanks dkanada, the new 0.5.0 version apparently solved the issue. I'm not experiencing those crashes anymore; but the grid size is now limited to 10 rows, maybe this could also be the reason?
