### ISSUE TITLE
When app removed its widget remains

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#326] opened 2018-01-24 06:42 UTC
re: https://github.com/OpenLauncherTeam/openlauncher/issues/217
The wrong behavior is like that: the place of the widget is marked "cannot create widget" and that frame is unable to be dragged nor deleted.

**Comment by just-Nob** [comment] 2018-10-12 22:02
If you are reporting crashes or expected behaviour then please check if all requirements are fulfilled #### General information

* **App version:** 0.5.12 (from F-Droid)
* **Android Version:** 8.1 Oreo

@ildar :
Unfortunately, your description is a little poor, but I've the same issue, so I'm going to "pimp" this issue... ;)

#### Expected result
**What is expected?** 
When a widget is removed, its place on the OpenLauncher's homescreen should be freed
In my case, this situation was caused due to the loss of an app's widget, caused by an app update  - thanks, Google, for making the nice SMS Messages app much more worst by kicking out the widget!!).

**What does happen instead?**
The widget's place on the homescreen is still covered by a "placeholder" (with the given text "cannot create widget"). This placeholder cannot be (re)moved or deleted in any way.





#### Steps to reproduce
* Install an older version of any app containing a widget, e.g. Google's SMS messages app.
* Place a widget on the homescreen.
* Update to app's latest version, which is missing the widget support.
* The latest step (update) may be substituted by deleting the app inter of the update, I guess (haven't tried this out).

**Comment by gsantner** [comment] 2021-01-25 22:01
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:

**Closed by gsantner** 2021-01-25 22:01 UTC
