### ISSUE TITLE
Reccurrent crash when updating or changing grid size

### ISSUE THREAD

**Issue by sardemff7** [OpenLauncherTeam/openlauncher#98] opened 2017-05-12 08:40 UTC
Or importing a backup with different size (since I don't use the default).
It even happened randomly when adding an app toqthe desktop (during the initial setup, since a previous crash forced me to wipe my config).

Here is the Java backtrace
```
Build version: 0.4.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-12 10:35:19 
Device: HUAWEI FRD-L09 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.benny.openlauncher.util.DatabaseHelper.getDesktop(DatabaseHelper.java:114)
	at com.benny.openlauncher.widget.Desktop.init(Desktop.java:76)
	at com.benny.openlauncher.activity.Home.initViews(Home.java:323)
	at com.benny.openlauncher.activity.Home.init(Home.java:247)
	at com.benny.openlauncher.activity.Home.access$200(Home.java:77)
	at com.benny.openlauncher.activity.Home$3.onPostExecute(Home.java:231)
	at com.benny.openlauncher.activity.Home$3.onPostExecute(Home.java:214)
	at android.os.AsyncTask.finish(AsyncTask.java:688)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:705)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by gsantner** [comment] 2017-05-26 12:16
duplicate of #133

**Closed by gsantner** 2017-05-26 12:16 UTC
