### ISSUE TITLE
Feature request. Infinite horizontal scrolling.

### ISSUE THREAD

**Issue by serebryakov-av** [OpenLauncherTeam/openlauncher#421] opened 2018-10-10 15:02 UTC
What an option to turn on infinite horizontal scrolling.

For example.
If I have 2 or more screens I can slide to 1st screen by scrolling to the right from the last screen.

**Comment by JohnVeness** [comment] 2018-11-04 20:46
Duplicate of #181.

**Closed** 2019-04-27 23:37 UTC
Labels: feature
