### ISSUE TITLE
App crashes when tapping anything on the settings menu.

### ISSUE THREAD

**Issue by hugojmaia** [OpenLauncherTeam/openlauncher#517] opened 2019-11-15 21:23 UTC
This begun about a couple versions back, initially I just stuck with it. Now that I'm looking to be able to configure things again (app feels slow as molasses after the latest update) and the competition on f-droid don't have the same mix of features and configurability (tried half a dozen).
Note, these crashes happen 100% of the time.
![Screenshot_20191115-180608](https://user-images.githubusercontent.com/8614893/68976508-a8857080-07d4-11ea-9bb5-5aa7516f6e42.png)
![Screenshot_20191115-182228](https://user-images.githubusercontent.com/8614893/68976618-f306ed00-07d4-11ea-8313-01f7cb381165.png)

General Information:

Phone model: Umidigi A1 Pro
OpenLauncher Version: 0.7.0
Android Version: 8.1.0
Custom ROM: None
Install Source: F-Droid

Stack log:
Build version: 0.7.0 
Build date: 1979-11-29 21:00:00 
Current date: 2019-11-15 18:02:51 
Device: A-gold A1_PRO 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at net.gsantner.opoc.util.ContextUtils.getResId(ContextUtils.java:119)
	at com.benny.openlauncher.fragment.SettingsMasterFragment.onPreferenceTreeClick(SettingsMasterFragment.java:30)
	at android.support.v7.preference.Preference.performClick(Preference.java:1173)
	at android.support.v7.preference.Preference.performClick(Preference.java:1148)
	at android.support.v7.preference.Preference$1.onClick(Preference.java:172)
	at android.view.View.performClick(View.java:6311)
	at android.view.View$PerformClick.run(View.java:24979)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by gsantner** [comment] 2019-11-19 22:54
please add version information and installation source.

**Comment by gsantner** [comment] 2019-11-19 23:26
@hugojmaia 
I couldn't reproduce the issue on current master, may be fixed in next update. (potential opoc update related).

Please report back if not fixed then.

**Closed by gsantner** 2019-11-19 23:26 UTC
